server {
  listen 80;
  server_name _;
  client_max_body_size 25M;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /api/docs {
    proxy_pass http://backend:3000/api/docs;
  }

  location = /api/docs-json {
    proxy_pass http://backend:3000/api/docs-json;
  }

  location = /api/docs-yaml {
    proxy_pass http://backend:3000/api/docs-yaml;
  }

  location ^~ /api/docs/ {
    proxy_pass http://backend:3000/api/docs/;
  }

  location /api/ {
    proxy_pass http://backend:3000/;
  }
}
